development:
   GIT_HUB_CLIENT_ID: ''
   GIT_HUB_CLIENT_SECRET: ''
   GITLAB_API_ENDPOINT: ''
   GITLAB_API_PRIVATE_TOKEN: ''
test:
   GIT_HUB_CLIENT_ID: ''
   GIT_HUB_CLIENT_SECRET: ''
   GITLAB_API_ENDPOINT: ''
   GITLAB_API_PRIVATE_TOKEN: ''
production:
   GIT_HUB_CLIENT_ID: ''
   GIT_HUB_CLIENT_SECRET: ''
   GITLAB_API_ENDPOINT: ''
   GITLAB_API_PRIVATE_TOKEN: ''
